In [93]:
import numpy as np
import scipy as sp 
import pandas as pd

from numpy import array as ar
import matplotlib.pyplot as plt
plt.style.use('ggplot')
import warnings
warnings.filterwarnings('ignore') 

import datetime
from pathlib import Path

In [94]:
#initial setting for record of registration
#reset every day
df=pd.DataFrame(columns=["NameList","HKIDList","PhoneList",
                         "VenueList","TimeList","ActList",
                        "VenueIDList","TimeIDList","ActIDList","index"])

In [98]:
#registration (run when anyone wants to book a sports venue)
dt = datetime.date.today() + datetime.timedelta(days=7)
date = dt.isoformat() #get date after 1 week

print("Booking for " + date + ":\n") #title

#information for person 1: (name, HKID, phone)

while True:
    name = input("Please enter full name for person 1: ")
    if name != "":
        break
    print("Invalid name.")
namels=[name]
    
while True:
    hkid = input("Please enter HKID for person 1: ")
    if hkid != "":
        break
    print("Invalid ID.")
hkidls=[hkid]

while True:
    phone = input("Please enter phone number for person 1: ")
    if phone != "" and phone.isdigit():
        break
    print("Invalid phone number.")
phonels=[phone]

while True:
    addPerson = input("Add another person? Y for yes, N for no : ")
    if addPerson=="Y" or addPerson=="N":
        break
    print("Invalid input. Please enter Y or N only.")

count = 1

#information for other people: (if applicable)

while addPerson == "Y":
    print("\n")
    count += 1
    
    while True:
        newname = input("Please enter full name for person " + str(count) + ": ")
        if newname != "":
            break
        print("Invalid name.")
    namels.append(newname)
    
    while True:
        newhkid = input("Please enter HKID for person " + str(count) + ": ")
        if newhkid != "":
            break
        print("Invalid ID.")
    hkidls.append(newhkid)
    
    while True:
        newphone = input("Please enter phone number for person " + str(count) + ": ")
        if newphone != "" and newphone.isdigit():
            break
        print("Invalid phone number.")
    phonels.append(newphone)
    
    while True:
        addPerson = input("Add another person? Y for yes, N for no : ")
        if addPerson=="Y" or addPerson=="N":
            break
        print("Invalid input. Please enter Y or N only.")

#confirm information
confirm=""
while confirm!="Y":
    print("\n")
    for i in range(count):
        print("Person "+str(i+1)+": "+namels[i]+", "+hkidls[i]+", "+phonels[i])
    print("Please check if the information above is correct.")
    confirm=input("Enter Y to confirm. Enter N to cancel. Enter a number to correct that person's information.")
    
    if confirm=="N":
        break
        
    elif confirm.isdigit():
        #change information
        print("\n")
        while True:
            newname = input("Please enter full name for person " + confirm + ": ")
            if newname != "":
                break
            print("Invalid name.")
        namels[int(confirm)-1]=newname
    
        while True:
            newhkid = input("Please enter HKID for person " + confirm + ": ")
            if newhkid != "":
                break
            print("Invalid ID.")
        hkidls[int(confirm)-1]=newhkid
    
        while True:
            newphone = input("Please enter phone number for person " + confirm + ": ")
            if newphone != "" and newphone.isdigit():
                break
            print("Invalid phone number.")
        phonels[int(confirm)-1]=newphone
        
    elif confirm!="Y":
        print("Invalid input.")
        
if confirm=="Y":
    print("Confirmed information.")
    prior=1
    venls=[]
    timels=[]
    actls=[]
    venidls=[]
    timeidls=[]
    actidls=[]
    #choose venue,time and activity (3 times for 3 priorities)
    #for simplicity, assume only 5 venues
    while prior<=3:
        print("""\n1: Chai Wan Sports Centre
2: Java Road Sports Centre
3: Cheung Sha Wan Sports Centre
4: Lai Chi Kok Sports Centre
5: Tseung Kwan O Sports Centre""")
        while True:
            venid=input("Choose a venue for priority "+str(prior)+": ")
            if venid=="1":
                venls.append("Chai Wan Sports Centre")
                break
            elif venid=="2":
                venls.append("Java Road Sports Centre")
                break
            elif venid=="3":
                venls.append("Cheung Sha Wan Sports Centre")
                break
            elif venid=="4":
                venls.append("Lai Chi Kok Sports Centre")
                break
            elif venid=="5":
                venls.append("Tseung Kwan O Sports Centre")
                break
            else:
                print("Invalid input. Input the number only.")
        venidls.append(int(venid))
            
        #for simplicity, assume only 0800-2200 available
        print("""\n8: 8-9am
9: 9-10am
10: 10-11am
......
20: 8-9pm
21: 9-10pm""")
        while True:
            timeid=input("Choose a time for priority "+str(prior)+": ")
            if timeid=="8":
                timels.append("0800-0900")
                break
            elif timeid=="9":
                timels.append("0900-1000")
                break
            elif timeid=="10":
                timels.append("1000-1100")
                break
            elif timeid=="11":
                timels.append("1100-1200")
                break
            elif timeid=="12":
                timels.append("1200-1300")
                break
            elif timeid=="13":
                timels.append("1300-1400")
                break
            elif timeid=="14":
                timels.append("1400-1500")
                break
            elif timeid=="15":
                timels.append("1500-1600")
                break
            elif timeid=="16":
                timels.append("1600-1700")
                break
            elif timeid=="17":
                timels.append("1700-1800")
                break
            elif timeid=="18":
                timels.append("1800-1900")
                break
            elif timeid=="19":
                timels.append("1900-2000")
                break
            elif timeid=="20":
                timels.append("2000-2100")
                break
            elif timeid=="21":
                timels.append("2100-2200")
                break
            else:
                print("Invalid input. Input the number only.")
        timeidls.append(int(timeid)-8)
        
        #for simplicity, assume only 5 sports activities
        print("""\n1: Basketball
2: Badminton
3: Table Tennis
4: Volleyball
5: Squash""")
        while True:
            actid=input("Choose an activity for priority "+str(prior)+": ")
            if actid=="1":
                actls.append("Basketball")
                break
            elif actid=="2":
                actls.append("Badminton")
                break
            elif actid=="3":
                actls.append("Table Tennis")
                break
            elif actid=="4":
                actls.append("Volleyball")
                break
            elif actid=="5":
                actls.append("Squash")
                break
            else:
                print("Invalid input. Input the number only.")
        actidls.append(int(actid))
        
        prior+=1
    print("\n")
    
    #show 3 choices
    for i in range(3):
        print("Priority "+str(i+1)+": "+venls[i]+", "+timels[i]+", "+actls[i])
    
    #add a list for index number for future internal use
    #no. of records/index = no. of people so higher chance to be drawn for more people
    indexls=[]
    for i in range(count):
        indexls.append(len(df.index)+i)
    #insert record to dataframe
    for i in range(count):
        df.loc[len(df.index)] = [namels,hkidls,phonels,venls,timels,actls,venidls,timeidls,actidls,indexls]

Booking for 2022-06-10:

Please enter full name for person 1: Nam6
Please enter HKID for person 1: ID6
Please enter phone number for person 1: 666
Add another person? Y for yes, N for no : N


Person 1: Nam6, ID6, 666
Please check if the information above is correct.
Enter Y to confirm. Enter N to cancel. Enter a number to correct that person's information.Y
Confirmed information.

1: Chai Wan Sports Centre
2: Java Road Sports Centre
3: Cheung Sha Wan Sports Centre
4: Lai Chi Kok Sports Centre
5: Tseung Kwan O Sports Centre
Choose a venue for priority 1: 1

8: 8-9am
9: 9-10am
10: 10-11am
......
20: 8-9pm
21: 9-10pm
Choose a time for priority 1: 8

1: Basketball
2: Badminton
3: Table Tennis
4: Volleyball
5: Squash
Choose an activity for priority 1: 1

1: Chai Wan Sports Centre
2: Java Road Sports Centre
3: Cheung Sha Wan Sports Centre
4: Lai Chi Kok Sports Centre
5: Tseung Kwan O Sports Centre
Choose a venue for priority 2: 2

8: 8-9am
9: 9-10am
10: 10-11am
......
20: 8-9pm
21: 9-10pm
Choose a time for priority 2: 9

1: Basketball
2: Badminton
3: Table Tennis
4: Volleyball
5: Squash
Choose an activity for priority 2: 2

1: Chai Wan Sports Centre
2: Java Road Sports Centre
3: Cheung Sha Wan Sports Centre
4: Lai Chi Kok Sports Centre
5: Tseung Kwan O Sports Centre
Choose a venue for priority 3: 3

8: 8-9am
9: 9-10am
10: 10-11am
......
20: 8-9pm
21: 9-10pm
Choose a time for priority 3: 10

1: Basketball
2: Badminton
3: Table Tennis
4: Volleyball
5: Squash
Choose an activity for priority 3: 3


Priority 1: Chai Wan Sports Centre, 0800-0900, Basketball
Priority 2: Java Road Sports Centre, 0900-1000, Badminton
Priority 3: Cheung Sha Wan Sports Centre, 1000-1100, Table Tennis

In [99]:
df

,NameList,HKIDList,PhoneList,VenueList,TimeList,ActList,VenueIDList,TimeIDList,ActIDList,index
0,"[Nam1, Nam2]","[ID1, ID2]","[111, 222]","[Chai Wan Sports Centre, Java Road Sports Cent...","[0800-0900, 0900-1000, 1000-1100]","[Basketball, Badminton, Table Tennis]","[1, 2, 3]","[0, 1, 2]","[1, 2, 3]","[0, 1]"
1,"[Nam1, Nam2]","[ID1, ID2]","[111, 222]","[Chai Wan Sports Centre, Java Road Sports Cent...","[0800-0900, 0900-1000, 1000-1100]","[Basketball, Badminton, Table Tennis]","[1, 2, 3]","[0, 1, 2]","[1, 2, 3]","[0, 1]"
2,[Nam3],[ID3],[333],"[Chai Wan Sports Centre, Java Road Sports Cent...","[0800-0900, 0900-1000, 1000-1100]","[Basketball, Badminton, Table Tennis]","[1, 2, 3]","[0, 1, 2]","[1, 2, 3]",[2]
3,"[Nam4, Nam5]","[ID4, ID5]","[444, 555]","[Chai Wan Sports Centre, Java Road Sports Cent...","[0800-0900, 0900-1000, 1000-1100]","[Basketball, Badminton, Table Tennis]","[1, 2, 3]","[0, 1, 2]","[1, 2, 3]","[3, 4]"
4,"[Nam4, Nam5]","[ID4, ID5]","[444, 555]","[Chai Wan Sports Centre, Java Road Sports Cent...","[0800-0900, 0900-1000, 1000-1100]","[Basketball, Badminton, Table Tennis]","[1, 2, 3]","[0, 1, 2]","[1, 2, 3]","[3, 4]"
5,[Nam6],[ID6],[666],"[Chai Wan Sports Centre, Java Road Sports Cent...","[0800-0900, 0900-1000, 1000-1100]","[Basketball, Badminton, Table Tennis]","[1, 2, 3]","[0, 1, 2]","[1, 2, 3]",[5]

In [100]:
#export dataframe of registration to csv file with its date in the file name
filepath = Path('csv/'+date+' registration.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
df.to_csv(filepath)

In [101]:
#initial setting for dataframe of allocation and record that is drawn but unsuccessful
#reset everyday
allocation=pd.DataFrame(index=["0800-0900","0900-1000","1000-1100","1100-1200","1200-1300",
                               "1300-1400","1400-1500","1500-1600","1600-1700","1700-1800",
                               "1800-1900","1900-2000","2000-2100","2100-2200"],
                        columns=["ChaiWanBasket","JavaBasket","CSWBasket","LCKBasket","TKOBasket",
                                "ChaiWanBadmin","JavaBadmin","CSWBadmin","LCKBadmin","TKOBadmin",
                                "ChaiWanTable","JavaTable","CSWTable","LCKTable","TKOTable",
                                "ChaiWanVoll","JavaVoll","CSWVoll","LCKVoll","TKOVoll",
                                "ChaiWanSqu","JavaSqu","CSWSqu","LCKSqu","TKOSqu"])

In [102]:
#allocation (run once per day after 2359)
while True:
    randomindex=np.random.randint(0,len(df)) #random choice for a record
    prior=0
    venidls=df.iloc[randomindex,6]
    timeidls=df.iloc[randomindex,7]
    actidls=df.iloc[randomindex,8]
    while prior<3:
        ven=venidls[prior]
        time=timeidls[prior]
        act=actidls[prior]
        venact=(act-1)*5+ven-1
        if allocation.isnull().iloc[time,venact]: #check if that slot is filled
            allocation.iloc[time,venact]=[df.iloc[randomindex,0],df.iloc[randomindex,1],df.iloc[randomindex,2]]
            break
        prior += 1
    indexls=df.iloc[randomindex,9]
    for i in indexls:
        df.drop(i,inplace=True) #drop the records that have been allocated (including those repeated)
    if len(df)==0: #all demand fulfilled, end allocation
        break
    if allocation.isnull().sum().sum()==0: #all slots filled, end allocation
        break

In [103]:
allocation

,ChaiWanBasket,JavaBasket,CSWBasket,LCKBasket,TKOBasket,ChaiWanBadmin,JavaBadmin,CSWBadmin,LCKBadmin,TKOBadmin,...,ChaiWanVoll,JavaVoll,CSWVoll,LCKVoll,TKOVoll,ChaiWanSqu,JavaSqu,CSWSqu,LCKSqu,TKOSqu
0800-0900,"[[Nam1, Nam2], [ID1, ID2], [111, 222]]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0900-1000,NaN,NaN,NaN,NaN,NaN,NaN,"[[Nam6], [ID6], [666]]",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000-1100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1100-1200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1200-1300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1300-1400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1400-1500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1500-1600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1600-1700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1700-1800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1800-1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1900-2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-2100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2100-2200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
#export dataframe of allocation to csv file with its date in the file name
from pathlib import Path  
filepath = Path('csv/'+date+' allocation.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
allocation.to_csv(filepath)